name: Release Builds

on: push

env:
  SME_DEPS_VERSION: "2023.11.14"
  SME_VERSION: "dune_copasi_2"
  CIBUILDWHEEL_VERSION: 2.16
  CIBW_BUILD_VERBOSITY: 3
  INSTALL_PREFIX: "/opt/smelibs"
  SUDOCMD: "sudo -E"
  MACOSX_DEPLOYMENT_TARGET: "11"
  OS_TARGET: "osx-arm64"

jobs:
  build:
    name: MacOS Arm64 sme GUI/CLI
    runs-on: macos-arm64-ssc
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.3"
      - run: ./init.sh
      - run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          path: ./artefacts/*
  wheel:
    name: MacOS Arm64 sme Wheels
    runs-on: macos-arm64-ssc
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.3"
      - run: ./init.sh
      - run: ./wheels.sh
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  release:
    needs: [build, wheel]
    if: github.repository == 'ssciwr/sme-osx-arm64' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: binaries
      - name: Upload binaries to tagged release
        # if this a tagged commit, upload binaries to github release for this tag
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
